"""
Markdown report generation for bug captures
"""
from pathlib import Path
from datetime import datetime
from typing import Dict, Any


REPORT_TEMPLATE = """# Bug Report: {bug_id}

**Date:** {date}  
**Time to Fix:** {time_to_fix} seconds ({time_to_fix_min} minutes)  
**Confidence:** {confidence}%

---

## 🔍 Root Cause

{root_cause}

---

## 🛠️ What Fixed It

{fix_explanation}

---

## 💡 Key Learning

{learning}

---

## 📝 Code Changes

```diff
{git_diff}
```

---

## 📊 Error Log

```
{error_log}
```

---

## 🏷️ Tags

{tags}

---

## 📂 Files Modified

{files_modified}

---

*Generated by Deja-Bug AI • Powered by Ollama & qwen2.5-coder:3b*
"""


def generate_markdown_report(
    bug_id: str,
    summary: Dict[str, Any],
    error_log: str,
    git_diff: str,
    files_modified: list[str],
    time_to_fix: int,
    confidence: float
) -> str:
    """
    Generate a markdown report for a captured bug.
    
    Args:
        bug_id: Unique bug identifier
        summary: LLM-generated summary (root_cause, fix_explanation, learning, tags)
        error_log: Original error log
        git_diff: Git diff showing the fix
        files_modified: List of modified files
        time_to_fix: Time taken to fix in seconds
        confidence: Match confidence (0-1)
        
    Returns:
        Formatted markdown string
    """
    tags_str = ", ".join(f"`{tag}`" for tag in summary.get("tags", []))
    files_str = "\n".join(f"- `{f}`" for f in files_modified) if files_modified else "None"
    
    return REPORT_TEMPLATE.format(
        bug_id=bug_id,
        date=datetime.now().strftime("%Y-%m-%d %H:%M:%S"),
        time_to_fix=time_to_fix,
        time_to_fix_min=round(time_to_fix / 60, 1),
        confidence=round(confidence * 100),
        root_cause=summary.get("root_cause", "N/A"),
        fix_explanation=summary.get("fix_explanation", "N/A"),
        learning=summary.get("learning", "N/A"),
        git_diff=git_diff if git_diff else "No code changes captured",
        error_log=error_log[:1000] if error_log else "No error log",  # Truncate
        tags=tags_str if tags_str else "None",
        files_modified=files_str
    )


def save_markdown_report(
    bug_id: str,
    markdown: str,
    output_dir: str = "~/.deja-bug/bugs"
) -> Path:
    """
    Save markdown report to disk.
    
    Args:
        bug_id: Unique bug identifier
        markdown: Markdown content
        output_dir: Directory to save reports
        
    Returns:
        Path to saved file
    """
    output_path = Path(output_dir).expanduser()
    output_path.mkdir(parents=True, exist_ok=True)
    
    file_path = output_path / f"{bug_id}.md"
    file_path.write_text(markdown)
    
    return file_path


def update_timeline_index(bug_id: str, summary: Dict[str, Any], output_dir: str = "~/.deja-bug"):
    """
    Update the main timeline index with new bug entry.
    
    Args:
        bug_id: Unique bug identifier
        summary: Bug summary
        output_dir: Output directory
    """
    index_path = Path(output_dir).expanduser() / "index.md"
    
    # Create or append to index
    entry = f"\n- [{datetime.now().strftime('%Y-%m-%d %H:%M')}] [{bug_id}](bugs/{bug_id}.md) - {summary.get('root_cause', 'N/A')[:50]}...\n"
    
    if index_path.exists():
        index_path.write_text(index_path.read_text() + entry)
    else:
        index_path.write_text(f"# Deja-Bug Timeline\n{entry}")
